slang_dict = {
    # Abbreviations & contractions
    "q": "what",
    "nt": "not",
    "w8": "wait",
    "bc": "because",
    "idk": "i do not know",
    "imo": "in my opinion",
    "brb": "be right back",
    "btw": "by the way",
    "omg": "oh my god",
    "lol": "laughing out loud",
    "wtf": "what the fuck",
    "lmfao": "laughing my fucking ass off",
    "rofl": "rolling on the floor laughing",
    'k9s': 'canines',
    "smh": "shaking my head",
    "yolo": "you only live once",
    "gunna": "going to",
    "gonna": "going to",
    "hes": "he is",
    "shes": "she is",
    "aint": "is not",
    "lemme": "let me",
    "gimme": "give me",
    "wanna": "want to",
    "gotta": "got to",
    "tryna": "trying to",
    "kinda": "kind of",
    "sorta": "sort of",
    "tho": "though",
    "coz": "because",
    "cuz": "because",
    "ya": "you",
    "nah": "no",
    "yeah": "yes",
    "hbu": "how about you",
    "idc": "i do not care",
    "ikr": "i know right",
    "mr": "mister",
    'ayy': 'hey',
    'duhhh': 'duh',
    'pls': 'please',
    'ummm': 'um',
    "ish": "sort of",
    'outta': 'out of',
    'thru': 'through',
    'stfu': 'shut the fuck up',
    'lmao': 'laughing my ass off',
    'lolol': 'laugh out loud',
    'tbh': 'to be honest',
    'smh': 'shaking my head',
    'yolo': 'you only live once',
    'btw': 'by the way',
    'iz': 'is',
    'hmmm': 'hmm',
    'mins': 'minutes',
    'dindu': 'did not do',
    'k9': 'canine',
    'np': 'no problem',
    # Slang/shortened words
    "somethin": "something",
    "nothin": "nothing",
    "goin": "going",
    "comin": "coming",
    "watchin": "watching",
    "talkin": "talking",
    "lookin": "looking",
    "doin": "doing",
    "thinkin": "thinking",
    "boooshit": "bullshit",
    "gunna": "going to",
    'tellin': 'telling',
    'tryin': 'trying',
    'reffering': 'referring',
    'interviwing': 'interviewing',
    'fucken': 'fucking',
    'gettin': 'getting',
    'showin': 'showing',
    'cussin': 'cussing',
    'protestin': 'protesting',
    'mutherfuckin': 'motherfucking',
    'mutherfucker': 'motherfucker',
    'mothafuckin': 'motherfucking',
    'mothafuckas': 'motherfuckers',
    'freakin': 'freaking',
    'awakes': 'wakes up',
    'tru': 'true',
    'fuxking': 'fucking',
    # Visual/emotional expressions
    ":)": "smile",
    ":(": "sad",
    ":D": "big_smile",
    "<3": "love",
    ":-)": "smile",
    ":'(": "crying",
    "ooo": "oh",
    "booo": "oh",
    'woweee': 'wow',
    # Other
    "pussyfootin": "hesitating",
    'assss': 'ass',
    'dumbest': 'dumb',
    'clueless': 'not aware',
}

correction_dict = {
    "messege": "message",
    "hessitate": "hesitate",
    "recieve": "receive",
    "definately": "definitely",
    "seperated": "separated",
    "occured": "occurred",
    "untill": "until",
    "thier": "their",
    "goverment": "government",
    "wierd": "weird",
}

